(tests
 (names test_model_checking test_game_export test_pretty_print)
 (deps (source_tree data))
 (libraries naive_modcheck_coalg_parsers
            naive_modcheck_coalg_logics
            naive_modcheck_coalg_common
            naive_modcheck_coalg_checker
            naive_modcheck_coalg_export
            core
            ounit2
            yojson)
 (preprocess (pps ppx_jane)))
